config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :annonces
  

  root to: 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base

	belongs_to :user
	
	def self.validate_zip_code(zipcode)
		if zipcode.length == 5 or zipcode.length == 0
			return true
		else
			return false
		end
	end

	def maj_date_last_annonce(date)
		self.dateLastAnnonce = date
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :annonces

  after_create :send_admin_mail
  def send_admin_mail
  	Mailer.welcome(self).deliver_now
  	if (User.count == 1)
  		HardWorker.perform_async
  	end
  end

  before_destroy :destroy_all_annonces_from_user
  def destroy_all_annonces_from_user
    @annonces = Annonce.where(user_id: self.id)
    @annonces.each do |annonce|
      annonce.destroy
    end 
  end
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    @annonces = Annonce.all
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @terme = params["terme"]
    @typeProduit = params["typeProduit"]
    @region = params["region"]
    @codePostal = params["codePostal"]
    @url = "http://www.leboncoin.fr/#{@typeProduit.downcase}/offres/#{@region.downcase}/?f=a&th=1&q=#{@terme.downcase}&location=#{@codePostal}"
    @newAnnonce = {
      :titre => params["annonce"]["titre"],
      :urlRecherche => @url,
      user_id: current_user.id
    }
    @annonce = Annonce.new(@newAnnonce)
    if (Annonce.validate_zip_code(@codePostal))
      respond_to do |format|
        if @annonce.save
          format.html { redirect_to @annonce, notice: 'Annonce was successfully created.' }
          format.json { render :show, status: :created, location: @annonce }
          # puts "http://www.leboncoin.fr/#{@typeProduit.downcase}/offres/#{@region.downcase}/?f=a&th=1&location=#{@codePostal}"
          # HardWorker.perform_async("http://www.leboncoin.fr/#{@annonce.typeProduit.downcase}/offres/#{@annonce.region.downcase}/?f=a&th=1&location=#{@annonce.codePostal}")
        else
          format.html { render :new }
          format.json { render json: @annonce.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "Le champ code postal doit être vide ou comporter exactement 5 chiffres"
      render :new
    end
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    @terme = params["terme"]
    @typeProduit = params["typeProduit"]
    @region = params["region"]
    @codePostal = params["codePostal"]
    @url = "http://www.leboncoin.fr/#{@typeProduit.downcase}/offres/#{@region.downcase}/?f=a&th=1&q=#{@terme.downcase}&location=#{@codePostal}"
    @updatedAnnonce = {
      :titre => params["annonce"]["titre"],
      :urlRecherche => @url
    }
    if (Annonce.validate_zip_code(@codePostal))
      respond_to do |format|
        if @annonce.update(@updatedAnnonce)
          format.html { redirect_to @annonce, notice: 'Annonce was successfully updated.' }
          format.json { render :show, status: :ok, location: @annonce }
          # puts "http://www.leboncoin.fr/#{@annonce.typeProduit.downcase}/offres/#{@annonce.region.downcase}/?f=a&th=1&location=#{@annonce.codePostal}"
          # HardWorker.perform_async("http://www.leboncoin.fr/#{@annonce.typeProduit.downcase}/offres/#{@annonce.region.downcase}/?f=a&th=1&location=#{@annonce.codePostal}")
        else
          format.html { render :edit }
          format.json { render json: @annonce.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "Le champ code postal doit être vide ou comporter exactement 5 chiffres"
      render :new
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    respond_to do |format|
      format.html { redirect_to annonces_url, notice: 'Annonce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params.require(:annonce).permit(:titre, :urlRecherche)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:nom, :prenom, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:nom, :prenom, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        Mailer.welcome(@user).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nom, :prenom, :mail, :login, :pass)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
	  	@annonces = Annonce.all
	  	render "annonces/index"
	end
  end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annonces/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@annonce, remote: remote, html: {role: :form, 'data-model' => 'annonce'}) do |f| %>
  <% if @annonce.errors.any? %>
    <div id="error_explanation" >
      <h3><%= pluralize(@annonce.errors.count, "error") %> prohibited this annonce from being saved:</h3>

      <ul>
      <% @annonce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-offset-1">
    <div class="field">
      <%= f.label "Titre :" %><br>
      <%= f.text_field :titre %>
    </div>
    <div class="field">
      <%= f.label "Description :" %><br>
      <%= text_field_tag :terme %>
    </div>
    <div class="field">
      <%= f.label "Type de produit :" %><br>
      <%= select_tag :typeProduit, options_for_select(['Toutes_categories','_EMPLOI_','Offres_d_emploi','_VEHICULES_','Voitures','Motos','Caravaning','Utilitaires','Equipement_Auto','Equipement_Moto','Equipement_Caravaning','Nautisme','Equipement_Nautisme','_IMMOBILIER_','Ventes_immobilieres','Locations','Colocations','Bureaux_Commerces','_VACANCES_','Locations_Gites','Chambres_d_hotes','Campings','Hotels','Hebergements_insolites','_MULTIMEDIA_','Informatique','Consoles_Jeux_video','Image_Son','Telephonie','_MAISON_','Ameublement','Electromenager','Arts_de_la_table','Decoration','Linge_de_maison','Bricolage','Jardinage','Vetements','Chaussures','Accessoires_Bagagerie','Montres_Bijoux','Equipement_bebe','Vetements_bebe','_LOISIRS_','DVD_Films','CD_Musique','Livres','Animaux','Velos','Sports_Hobbies','Instruments_de_musique','Collection','Jeux_Jouets','Vins_Gastronomie','_MATERIEL_PROFESSIONNEL_','Materiel_Agricole','Transport_Manutention','BTP_Chantier_Gros-oeuvre','Outillage_Materiaux_2nd-oeuvre','Équipements_Industriels','Restauration_Hôtellerie','Fournitures_de_Bureau','Commerces_Marches','Materiel_Medical','_SERVICES_','Prestations_de_services','Billetterie','Evenements','Cours_particuliers','Covoiturage','Autres']) %>
    </div>
    <div class="field">
      <%= f.label "Région :" %><br>
      <%= select_tag :region, options_for_select(['Alsace','Aquitaine','Auvergne','Basse_Normandie','Bourgogne','Bretagne','Centre','Champagne_Ardenne','Corse','Franche_Comte','Haute_Normandie','Ile_de_France','Languedoc_Roussillon','Limousin','Lorraine','Midi_Pyrenees','Nord_Pas_De_Calais','Pays_De_La_Loire','Picardie','Poitou_Charentes','Provence_Alpes_Cote_d_Azur','Rhone_Alpes','Guadeloupe','Martinique','Guyane','Reunion']) %>
    </div>
    <div class="field">
      <%= f.label "Code postal :" %><br>
      <%= number_field_tag :codePostal %>
    </div>
    <div class="actions"> 
      <%= f.submit "Créer", :class => 'btn btn-default'%>
    </div>
  </div>
<% end %>

app/views/annonces/edit.html.erb
<div class='col-md-offset-1'><h3>Editer Annonce</h3></div>

<%= render 'form' %>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Voir</button>'.html_safe, @annonce %> |
<%= link_to '<button class="btn btn-default">Retour</button>'.html_safe, annonces_path %>

app/views/annonces/index.html.erb
<div id="annonce_table" class='form-group col-md-offset-1'><h3>Listing Annonces</h3></div>
<div class="row" style="text-align=center">
<table class="table-hover col-md-8 col-md-offset-2">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Url de recherche</th>
      <th colspan="3">Edition</th>
    </tr>
  </thead>

  <tbody>
    <% if current_user %>
      <% @annonces = Annonce.where(user_id: current_user.id) %>
    <% end %>
    <% @annonces.each do |annonce| %>
      <tr>
        <td><%= annonce.titre %></td>
        <td><%= annonce.urlRecherche %></td>
        <td><%= link_to '<button class="btn btn-default">Voir</button>'.html_safe, annonce %></td>
        <td><%= link_to '<button class="btn btn-default">Editer</button>'.html_safe, edit_annonce_path(annonce) %></td>
        <td><%= link_to '<button class="btn btn-default">Supprimer</button>'.html_safe, annonce, method: :delete, data: { confirm: 'Êtes-vous sur(e) ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br />
<div>
<%= link_to '<button class="col-md-offset-1 btn btn-default">Créer annonce</button>'.html_safe, new_annonce_path %>

</div>

app/views/annonces/new.html.erb
<div class='col-md-offset-1'><h3>Nouvelle Annonce</h3></div>

<%= render 'form' %>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Retour</button>'.html_safe, annonces_path %>

app/views/annonces/show.html.erb
<div class='form-group col-md-offset-1'><h3>Détails Annonce</h3></div>

<div class='form-group col-md-offset-1'>
  <div class='field'>
    <strong>Titre:</strong>
    <%= @annonce.titre %>
  </div>

  <div class='field'>
    <strong>Url recherchee:</strong>
    <%= @annonce.urlRecherche %>
  </div>
</div>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Editer</button>'.html_safe, edit_annonce_path(@annonce) %> |
<%= link_to '<button class="btn btn-default">Retour</button>'.html_safe, annonces_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LanglePasTropMal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
  <div zclass="col-md-8 col-md-offset-2">
     <div class="text-center">
       <h2>L'angle Pas Trop Mal<small> par Baptiste Lanusse & Jérémie Lecornu</small></h2>
        <div class="row">
          
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <% if flash[:error] %>
            <p class="alert alert-danger"><%= flash[:error] %></p>
          <% end %>
        </div>
        <div>
          <% if user_signed_in? %>
            Bienvenue <strong><%= current_user.prenom %></strong>.
            <button class="btn btn-default"><%= link_to 'Editer profil', edit_user_registration_path, :class => 'navbar-link' %></button>
            <button class="btn btn-default"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></button>
          <% else %>
            <div>Veuillez vous identifier ou créer un compte pour accéder aux fonctionnalités du site.</div>
            <div>
            <button class="btn btn-default"><%= link_to "Créer compte", new_user_registration_path, :class => 'navbar-link'  %></button>
            <button class="btn btn-default"><%= link_to "Se connecter", new_user_session_path, :class => 'navbar-link'  %></button>
            </div>
          <% end %>

        </div>
    </div>
    
  </div>
  </div>
  <div class="row">
    <div class="text-muted">
      <div class="text-left">    
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-offset-1">
  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-offset-1"><h3>Editing User</h3></div>

<%= render 'form' %>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Show</button>'.html_safe, @user %>
<%= link_to '<button class="col-md-offset-1 btn btn-default">Back</button>'.html_safe, users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class='form-group col-md-offset-1'><h3>Liste des utilisateurs</h3></div>
<div class="row" style="text-align=center">
<table class="table-hover col-md-8 col-md-offset-2">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th colspan="3">Edition</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nom %></td>
        <td><%= user.prenom %></td>
        <td><%= link_to '<button class="btn btn-default">Voir</button>'.html_safe, user %></td>
        <td><%= link_to '<button class="btn btn-default">Editer</button>'.html_safe, edit_user_path(user) %></td>
        <td><%= link_to '<button class="btn btn-default">Supprimer</button>'.html_safe, user, method: :delete, data: { confirm: 'Êtes-vous sur(e) ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br />
<div>
<%= link_to '<button class="col-md-offset-1 btn btn-default">Nouvel utilisateur</button>'.html_safe, new_user_path %>
</div>

app/views/users/new.html.erb
<div  class='col-md-offset-1'><h3>Nouvel Utilisateur</h3></div>

<%= render 'form' %>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Retour</button>'.html_safe, users_path %>

app/views/users/show.html.erb
<div class='form-group col-md-offset-1'><h3>Informations Utilisateurs</h3></div>

<div class='form-group col-md-offset-1'>
<p>
  <strong>Nom:</strong>
  <%= @user.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @user.prenom %>
</p>
</div>

<%= link_to '<button class="col-md-offset-1 btn btn-default">Editer</button>'.html_safe, edit_user_path(@user) %>
<%= link_to '<button class="col-md-offset-1 btn btn-default">Retour</button>'.html_safe, users_path %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <button class="btn btn-default"><%= link_to 'Annonces'.html_safe, annonces_path %></button>
<% end %>